"""Initial migration.

Revision ID: aa4485ea841d
Revises: 
Create Date: 2024-09-20 13:26:26.926837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4485ea841d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_verified')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
